### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by prashant1146** [prashant1146/Hactober2022#1]
You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image [in-place](https://en.wikipedia.org/wiki/In-place_algorithm), which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

![mat1](https://user-images.githubusercontent.com/115659142/195417481-266286c2-d9d9-44dc-b3f9-ca7db67450c2.jpg)

**Comment by palprashant2002** [comment]
Please Assign this issue to me...

**Comment by ruturaj-gh** [comment]
Hey @prashant1146 can i do this one too

**Comment by Pheonix-001** [comment]
plz assign this issue to me

**Comment by AKG1301** [comment]
Please assign this task to me

**Comment by ruturaj-gh** [comment]
#15 

> Please assign this task to me
