### ISSUE TITLE
Basic introduction of various functions of Pandas library

### ISSUE THREAD

**Issue by prashant1146** [prashant1146/Hactober2022#11]
Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real-world data analysis in Python.

**Comment by palprashant2002** [comment]
Please assign this issue to me...

**Comment by AKG1301** [comment]
Please assign this task to me

**Comment by AKG1301** [comment]
I have already send the pr.please check.
Link:
https://github.com/prashant1146/Hactober2022/pull/17#issue-1408512508

**Comment by AKG1301** [comment]
please check the pr.


> I have already send the pr.please check. Link: [#17 (comment)](https://github.com/prashant1146/Hactober2022/pull/17#issue-1408512508)

**Comment by Shreya111111** [comment]
please assign the issue to me

**Comment by prashant1146** [comment]
I have merged your PR @AKG1301.

**Comment by KrishKumar3004** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by ChandniJha630** [comment]
Please assign this issue to me
