### ISSUE TITLE
Various functions of Matplotlib library of Python

### ISSUE THREAD

**Issue by prashant1146** [prashant1146/Hactober2022#12]
Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension NumPy. It provides an object-oriented API for embedding plots into applications using general-purpose GUI toolkits like Tkinter, wxPython, Qt, or GTK.

**Comment by palprashant2002** [comment]
Please assign this issue to me...

**Comment by AKG1301** [comment]
please assign this task to me

**Comment by AKG1301** [comment]
I have submitted my PR. please check my pr.
https://github.com/prashant1146/Hactober2022/pull/60#issue-1410247555
