### ISSUE TITLE
Create a url shortner

### ISSUE THREAD

**Issue by prashant1146** [prashant1146/Hactober2022#23]
Write a program to generate a url shortner which accepts a url generate its shorten form and also if a shorten url is given return the original url.

**Comment by ssghait007** [comment]
@prashant1146 Is this required in cpp only ? or other language would also work

**Comment by prashant1146** [comment]
You can do it any language...

**Comment by prashant1146** [comment]
> @prashant1146 Is this required in cpp only ? or other language would also work

you can do it in any language.

**Comment by palprashant2002** [comment]
Please assign this issue to me...

**Comment by hem7275** [comment]
Hey prashant can I resolve this issue.
