### ISSUE TITLE
Largest Perimeter Triangle

### ISSUE THREAD

**Issue by prashant1146** [prashant1146/Hactober2022#3]
Given an integer array nums , return the largest perimeter of a triangle with a non-zero area, formed from three of these lengths. If it is impossible to form any triangle of a non-zero area, return 0.

**Comment by palprashant2002** [comment]
Please assign this issue to me...

**Comment by ruturaj-gh** [comment]
Please assign this issue to me

**Comment by Pheonix-001** [comment]
plz assign this issue to me

**Comment by AKG1301** [comment]
Pls assign this task to me

**Comment by Shreya111111** [comment]
plzz assign this issue to me

**Comment by Jyotisaini-2001** [comment]
Hii, I want to contribute in this issue.
Please assign this issue to me @prashant1146
