### ISSUE TITLE
Write program of Sieve of Eratosthene in Python

### ISSUE THREAD

**Issue by Anime-01** [prashant1146/Hactober2022#36]

**Comment by AKG1301** [comment]
@prashant1146 please check this pr also.
link: https://github.com/prashant1146/Hactober2022/pull/54#issue-1410160286

**Comment by Nimesh-21** [comment]
Can I do this?

**Comment by AKG1301** [comment]
> @prashant1146 please check this pr also. link: [#54 (comment)](https://github.com/prashant1146/Hactober2022/pull/54#issue-1410160286)

Already merged. Completed
