### ISSUE TITLE
Write a program to find Maximum Product Subarray in an Array in C++

### ISSUE THREAD

**Issue by SakshiMishra1** [prashant1146/Hactober2022#37]

**Comment by SakshiMishra1** [comment]
Hi @prashant1146 
please check PR #38

**Comment by KrishKumar3004** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by SanjoySaha24** [comment]
I want to contribute. Please assign it @prashant1146 as my first contribution for hacktoberfest 2022.

**Comment by hem7275** [comment]
Hey! I would like to contribute. Please assign it to me.
