### ISSUE TITLE
create a program to find  roots of quadratic equation in python.

### ISSUE THREAD

**Issue by Narut-Uchiha** [prashant1146/Hactober2022#44]

**Comment by KrishKumar3004** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by pallavi2031** [comment]
can you assign this issue I want to contribute .

**Comment by C-V-Anish** [comment]
Please assign me this issue. I would like to contribute.

**Comment by amanaggarwal06** [comment]
Hey, I wanted to do this.
Can you please assign it to me?
