### ISSUE TITLE
Write program of binary search in python.

### ISSUE THREAD

**Issue by Narut-Uchiha** [prashant1146/Hactober2022#45]

**Comment by himanshujaindev** [comment]
@prashant1146  Can you please assign this issue to me. Thanks.

**Comment by akashbiswas0** [comment]
@prashant1146 pls assign it to me

**Comment by himanshujaindev** [comment]
Please merge the PR #56 and close this issue. THANKS

**Comment by pallavi2031** [comment]
may you please assign this issue I want to contribute.

**Comment by akashbiswas0** [comment]
#72 merge this PR @prashant1146
