### ISSUE TITLE
Write a program to merge two sorted linked list such that resultant list is also sorted.

### ISSUE THREAD

**Issue by Aaditya1612** [prashant1146/Hactober2022#52]

**Comment by Aaditya1612** [comment]
Please assign this to me under hacktoberfest

**Comment by KrishKumar3004** [comment]
Hey! I would like to contribute. Please assign it to me.

**Comment by SanjoySaha24** [comment]
I want to contribute. Please assign it @prashant1146  as my first contribution for hacktoberfest 2022.
