### ISSUE TITLE
Leetcode Daily

### ISSUE THREAD

**Issue by Jayant-001** [prashant1146/Hactober2022#7]
Contribute Leetcode Daily question's solution with Question number and Date

**Comment by ruturaj-gh** [comment]
hey can you assign it to me

**Comment by palprashant2002** [comment]
Hello, Please assign this to me...

**Comment by Pheonix-001** [comment]
plz assign this issue to me

**Comment by AKG1301** [comment]
plz assign this issue to me

**Comment by Jyotisaini-2001** [comment]
Hii, I am interested. Please assign me this issue.
