### ISSUE TITLE
Given two strings S1 and S2, check whether S1 is substring of S2 or not.

### ISSUE THREAD

**Issue by hem7275** [prashant1146/Hactober2022#82]
eg1  intput -->
        S1 = abc
        S2 = fkjdfabcfgnk
        output--> YES
eg2 input-->
       S1 = fdg
       s2 = fdc
       output-->NO

**Comment by pallavi2031** [comment]
can you assign this issue I want to contribute.

**Comment by blieve16** [comment]
Please check PR #87

**Comment by omnaladkar** [comment]
hey pls assign me i want to contribute in c++ lang

**Comment by surreal30** [comment]
Hey please assign this to me.

**Comment by saishubham468** [comment]
Hi @hem7275 i would like to contribute to this issue could you assign me this issue.
